alias reload!='. ~/.zshrc'

alias cls='clear' # Good 'ol Clear Screen command
alias c='clear'
alias l='ls -al'
alias ll='ls -lartG'
alias ..='cd ..'
alias port_listen='sudo lsof -iTCP -sTCP:LISTEN -n -P'
alias dotfiles='cd ~/.dotfiles'
alias subl="/Applications/Sublime\ Text.app/Contents/SharedSupport/bin/subl"
alias work="cd /Users/ameyap/workplace"
alias cloud="ssh clouddesk"
alias other="cd /Users/ameyap/other"
alias ui='cd /Users/ameyap/workplace/DataCraftConsoleWebsite'
alias dpg='cd /Users/ameyap/workplace/DatacraftPublisherGateway'
alias ingestion='cd /Users/ameyap/workplace/DataCraftIngestion'
alias api='cd /Users/ameyap/workplace/DatacraftApiService'
alias sound_restart='sudo launchctl stop com.apple.audio.coreaudiod && sudo launchctl start com.apple.audio.coreaudiod'

alias bb=brazil-build
alias bba='brazil-build apollo-pkg'
alias bball='brc --allPackages'
alias bbb='brc --allPackages brazil-build'
alias bbr='brc brazil-build'
alias bbra='bbr apollo-pkg'
alias brc=brazil-recursive-cmd
alias bre=brazil-runtime-exec
alias bws='brazil ws'
alias bwscreate='bws create -n'
alias bwsuse='bws use --gitMode -p'