alias reload!='. ~/.zshrc'

alias cls='clear' # Good 'ol Clear Screen command
alias c='clear'
alias l='ls -al'
alias ll='ls -lartG'
alias scrambleutil='java -cp /Users/ameya.phadke/Documents/workspace/TalentNetwork/web/WEB-INF/classes:/Users/ameya.phadke/Documents/workspace/TalentNetwork/lib/log4j.jar:/Users/ameya.phadke/Documents/workspace/TalentNetwork/lib/commons-lang.jar com.jobvite.utils.ScrambleUtil'
alias tn='cd ~/Documents/workspace/Talentnetwork'
alias work='cd ~/Documents/workspace'
alias ..='cd ..'
alias tomcat='cd $TOMCAT'
alias catalina='$TOMCAT/bin/catalina.sh'
alias catalinal='tail -f $TOMCAT/logs/catalina.out'
alias catalina_stop='$TOMCAT/bin/catalina.sh stop'
alias catalina_start='$TOMCAT/bin/catalina.sh start'
alias catalinac='rainbow --config=tomcat -- tail -f $TOMCAT/logs/catalina.out'
alias catalinag='catalinal | grep -i "Deploying\|initialization completed"'
alias catalinae='catalinal | grep -i "Deploying\|startup failed"'
alias wowza='cd /Library/WowzaStreamingEngine'
alias port_listen='sudo lsof -iTCP -sTCP:LISTEN -n -P'
alias awsmfa='python /Users/ameya.phadke/Documents/workspace/aws-mfa/aws_mfa.py qa arn:aws:iam::086741701953:mfa/ameya'
alias awsmfaprod='python /Users/ameya.phadke/Documents/workspace/aws-mfa/aws_mfa.py prod arn:aws:iam::104086177496:mfa/ameya'
alias dotfiles='cd ~/.dotfiles'

